name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Ensure output directory exists
        run: mkdir -p ./output

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: moisesxtian
          output_path: ./output/github-snake.svg

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin git@github.com:moisesxtian/moisesxtian.git  # Set remote to SSH

      - name: Commit and Push the generated snake svg to the output branch
        run: |
          git checkout -b output
          git add ./output/github-snake.svg
          git commit -m "Update snake animation"
          git push --force origin output
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Use your secret SSH key
